### ISSUE TITLE
Saas-website sketches

### ISSUE THREAD

**Issue by jessicali673** [jessicali673/saas-website#1]
[li-jessica-3-coding-sketch.pdf](https://github.com/jessicali673/saas-website/files/4449525/li-jessica-3-coding-sketch.pdf)

Hey Christina!
Here are my sketches for the saas-website final
I listed 5 questions in green boxes

Thanks!
*edit *
Question 4 (social badge hover) was covered in class!
I will make my features page a table 

@muxlowc

**Comment by muxlowc** [comment]
@jessicali673  These look great! To answer your questions:

1) yes, you can for sure use grids to put images/captions - for the island, im assuming you mean having wide margins on the left and right? You could add a class of "max-length" or "wrapper" to your surrounding div (I would do this rathe than just using an island, as it likely wont be wide enough/your grid will still keep growing when you view it on a very large screen

2) Those stylized line breaks may need to be an image, or just do a border bottom on your sections (this way would be just a simple line)

3) You may just do a hover state - carousels are a bit annoying to code, so don't worry about making it function :)

4) I think it was web dev 3, week 9? - but dont worry about making them hover right now (you wont lose marks on that)

5) Yes! a username can just be for=/id="name"

**Comment by muxlowc** [comment]
@jessicali673  to add to the above, just make sure you include a table on your features page somehow!
