### ISSUE TITLE
Need help with aligning icons for SAAS

### ISSUE THREAD

**Issue by jessicali673** [jessicali673/saas-website#3]
Hello! 
I need help with aligning these icons to make it look like shown below
![Screen Shot 2020-04-20 at 4 04 20 PM](https://user-images.githubusercontent.com/55094160/79794643-9ded7b00-8320-11ea-9a29-93c9271f00e9.png)
I am trying to use grid classes but it doesn't seem to be working, I also can't put the caption below the icon instead of beside it. 
Any ideas?

Thank you for your time! 

@HannahDelaney,

**Comment by jessicali673** [comment]
**UPDATE:** 
Hey Hannah, I managed to figure out how to do this!

The only thing is how do I center the icons so that it is directly above the caption?
currently it looks like this: 
![Screen Shot 2020-04-20 at 4 35 56 PM](https://user-images.githubusercontent.com/55094160/79797315-08081f00-8325-11ea-8c08-f6239c4de86e.png)

**Comment by HannahDelaney** [comment]
Nicely done solving the first stage of this! 👍 

Try adding the class `.unit-content-center` to the same level as the `.unit` classes, and it should centre the items for you!

**Comment by jessicali673** [comment]
It worked thank you!
